spring.profiles.active=dev
spring.datasource.url=jdbc:h2:file:./data/MyDB
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=db
spring.datasource.password=1234
spring.h2.console.enabled=true
spring.h2.console.settings.trace=false
spring.h2.console.path=/h2-console
server.error.include-message=always
logging.level.org.springframework=ERROR
logging.pattern.console = %green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
server.port=8443
server.ssl.key-store=${KEY_STORE}
server.ssl.key-store-password=${KEY_STORE_PASSWORD}
server.ssl.key-password=${KEY_PASSWORD}